[workspace]
members = [
    "cli", "glue", "glue_derive", "engine", "core",
    "extensions/novelpub", "extensions/royalroad",
    "clients/cli",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true