[workspace]
members = [
    "crates/bundle",
    "crates/cli",
    "crates/core",
    "crates/engine",
    "crates/ffi",
    "crates/glue",
    "crates/glue_derive",
    "extensions/novelpub",
    "extensions/royalroad",
    "clients/cli",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true