[workspace]
members = [
    "crates/bundle",
    "crates/cli",
    "crates/core",
    "crates/engine",
    "crates/ffi",
    "crates/glue",
    "crates/glue_derive",
    "extensions/novelpub",
    "extensions/royalroad",
    "clients/cli",
]

[workspace.dependencies.chrono]
version = "0.4.22"
default-features = false
features = ["clock", "iana-time-zone", "oldtime", "std", "time", "serde"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true