[workspace]
members = [
    "cli", "glue", "glue_derive", "engine", "core", "extensions/novelpub", "extensions/royalroad",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort' 
strip = true