[workspace]
members = [
    "packages/cli", "packages/glue", "packages/glue_derive", "packages/engine", "packages/core",
    "extensions/novelpub", "extensions/royalroad",
    "plugins/bundle",
    "clients/cli",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true