name: quille
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  ffi: ^2.0.1
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.6
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  name: Quille
  description: 'Bindings to Quille'
  output: 'lib/bindings/generated_bindings.dart'
  headers: 
    entry-points:
      - 'lib/bindings/bindings.h'